name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/xybp888/iOS-SDKs | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}
          save-always: true

      - name: Prepare Theos
        uses: Randomblock1/theos-action@main
        with:
          theos-sdks: 'https://github.com/xybp888/iOS-SDKs'
          theos-sdks-branch: 'master'

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "Package built by ${{ matrix.os }}"
          path: ${{ github.workspace }}/packages/*.deb
