name: Build and release

on: [workflow_dispatch]

jobs:
  build:
    name: Build and release tweak
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download SDK
        run: |
          TEMP_DIR=$(mktemp -d)
          git clone --no-checkout $GIT_URL $TEMP_DIR
          cd $TEMP_DIR
          git sparse-checkout init --cone
          git sparse-checkout set $FOLDER_PATH
          git checkout $GIT_BRANCH
          cd ..
          mv $TEMP_DIR/$FOLDER_PATH $DEST_FOLDER
          rm -rf $TEMP_DIR
        env:
          GIT_URL: https://github.com/chrisharper22/sdks
          GIT_BRANCH: main
          FOLDER_PATH: iPhoneOS15.5.sdk
          DEST_FOLDER: ${{ github.workspace }}/theos/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@4
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        env:
          THEOS: ${{ github.workspace }}/theos
