name: Build and release

on: [workflow_dispatch]

jobs:
  build:
    name: Build and release tweak
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: brew install ldid dpkg make subversion

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: Download iOS 15.5 SDK
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS15.5.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        env:
          THEOS: ${{ github.workspace }}/theos
