name: Build and release

on: [workflow_dispatch]

jobs:
  build:
    name: Build and release tweak
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/xybp888/iOS-SDKs | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}
          save-always: true

      - name: Prepare Theos
        uses: Randomblock1/theos-action@main
        with:
          theos-sdks: 'https://github.com/xybp888/iOS-SDKs'
          theos-sdks-branch: 'master'

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Parse control file version
        id: parse_control
        run: |
          version=$(sed -n 's/^Version: //p' control | sed 's/~/-/g')
          echo "TWEAK_VERSION=$version" >> "$GITHUB_OUTPUT"
          
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          TWEAK_VERSION: ${{ steps.parse_control.outputs.TWEAK_VERSION }}
        with:
          tag_name: v${{ env.TWEAK_VERSION }}
          name: v${{ env.TWEAK_VERSION }}
          files: packages/*.deb
